import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'ar' | 'he';

interface LanguageContextType {
  currentLanguage: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation data
const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.services': 'Services',
    'nav.blog': 'Blog',
    'nav.contact': 'Contact Us',
    'nav.login': 'Login',
    'nav.dashboard': 'Dashboard',
    'nav.logout': 'Logout',
    'nav.welcome': 'Welcome',
    'nav.allServices': 'All Services',
    'nav.productListing': 'Product Listing',
    'nav.orderManagement': 'Order Management',
    'nav.paymentGateway': 'Payment Gateway',
    'nav.customerSupport': 'Customer Support',
    'nav.shippingDelivery': 'Shipping & Delivery',
    'nav.analyticsReports': 'Analytics & Reports',
    'nav.home1': 'Home1',
    'nav.home2': 'Home2',
    'language.english': 'English',
    'language.arabic': 'العربية',
    'language.hebrew': 'עברית',
    
    // Hero Section
    'hero.title': 'Transform Your E-Commerce Business',
    'hero.subtitle': 'Streamline operations, boost sales, and deliver exceptional customer experiences with our comprehensive e-commerce solutions.',
    'hero.cta': 'Get Started Today',
    'hero.learnMore': 'Learn More',
    
    // Home1 Page Sections
    'home1.categories.title': 'Shop by Category',
    'home1.categories.subtitle': 'Explore our wide range of categories and find exactly what you\'re looking for',
    'home1.featuredProducts.title': 'Featured Products',
    'home1.featuredProducts.subtitle': 'Handpicked products that our customers love the most',
    'home1.featuredProducts.addToCart': 'Add to Cart',
    'home1.featuredProducts.viewAll': 'View All Products',
    'home1.featuredProducts.showLess': 'Show Less',
    'home1.cart.title': 'Your Cart',
    'home1.cart.items': 'items',
    'home1.cart.total': 'Total',
    'home1.cart.clearCart': 'Clear Cart',
    'home1.cart.checkout': 'Checkout',
    'home1.cart.addedToCart': 'Added to cart! ✓',
    'home1.stats.title': 'Why Choose Us ?',
    'home1.stats.subtitle': 'We\'re committed to providing the best shopping experience with quality products and exceptional service',
    'home1.testimonials.title': 'What Our Customers Say',
    'home1.testimonials.subtitle': 'Don\'t just take our word for it - hear from our satisfied customers',
    'home1.testimonials.clickToSeeMore': 'Click to see more',
    'home1.testimonials.purchased': 'Purchased:',
    'home1.testimonials.verifiedBuyer': 'Verified Buyer',
    'home1.testimonials.premiumMember': 'Premium Member',
    'home1.testimonials.loyalCustomer': 'Loyal Customer',
    'home1.testimonials.weeksAgo': 'weeks ago',
    'home1.testimonials.monthAgo': 'month ago',
    'home1.testimonials.weekAgo': 'week ago',
    'home1.testimonials.content1': 'Amazing quality products and fast delivery. This is now my go-to online store!',
    'home1.testimonials.content2': 'The customer service is exceptional and the product range is incredible. Highly recommended!',
    'home1.testimonials.content3': 'I\'ve been shopping here for years and never been disappointed. Great prices and quality!',
    'home1.testimonials.content4': 'Fast shipping and excellent product quality. Will definitely shop here again!',
    'home1.testimonials.sarahJohnson': 'Sarah Johnson',
    'home1.testimonials.michaelChen': 'Michael Chen',
    'home1.testimonials.emilyRodriguez': 'Emily Rodriguez',
    'home1.testimonials.davidKim': 'David Kim',
    'home1.newsletter.title': 'Stay in the Loop',
    'home1.newsletter.subtitle': 'Get exclusive access to early bird deals, new product launches, and insider tips delivered straight to your inbox',
    'home1.newsletter.exclusiveDeals': 'Exclusive Deals',
    'home1.newsletter.exclusiveDealsDesc': 'Be the first to know about flash sales and limited-time offers',
    'home1.newsletter.newProducts': 'New Product Alerts',
    'home1.newsletter.newProductsDesc': 'Get notified when we launch exciting new products',
    'home1.newsletter.shoppingTips': 'Shopping Tips',
    'home1.newsletter.shoppingTipsDesc': 'Expert advice to help you make the best purchasing decisions',
    'home1.newsletter.emailLabel': 'Email Address',
    'home1.newsletter.emailPlaceholder': 'Enter your email address',
    'home1.newsletter.subscribe': 'Subscribe Now',
    'home1.newsletter.success': '🎉 Successfully subscribed! Welcome to the family!',
    'home1.newsletter.privacy': 'We respect your privacy. Unsubscribe at any time. No spam, ever.',
    
    // Home1 Categories and Products
    'home1.categories.electronics': 'Electronics',
    'home1.categories.fashion': 'Fashion',
    'home1.categories.homeGarden': 'Home & Garden',
    'home1.categories.sports': 'Sports',
    'home1.categories.books': 'Books',
    'home1.categories.beauty': 'Beauty',
    
    // Home1 Product Names
    'home1.products.premiumHeadphones': 'Premium Wireless Headphones',
    'home1.products.fitnessWatch': 'Smart Fitness Watch',
    'home1.products.ultraHdCamera': 'Ultra HD Camera',
    'home1.products.portableSpeaker': 'Portable Speaker',
    'home1.products.gamingLaptop': 'Gaming Laptop',
    'home1.products.wirelessEarbuds': 'Wireless Earbuds',
    'home1.products.smartphone': 'Smartphone',
    'home1.products.monitor4k': '4K Monitor',
    
    // Home1 Stats Labels
    'home1.stats.happyCustomers': 'Happy Customers',
    'home1.stats.productsSold': 'Products Sold',
    'home1.stats.support': 'Support',
    'home1.stats.satisfactionRate': 'Satisfaction Rate',
    
    // About Page
    'about.title': 'About us',
    'about.subtitle': '',
    'about.description': 'We are a leading e-commerce solutions provider, helping businesses of all sizes succeed in the digital marketplace.',
    'about.mission': 'Our Mission',
    'about.missionText': 'To empower businesses with innovative e-commerce tools that drive growth and customer satisfaction.',
    'about.vision': 'Our Vision',
    'about.visionText': 'To be the most trusted partner for e-commerce success worldwide.',
    'about.values': 'Our Values',
    'about.valuesSubtitle': 'The principles that guide everything we do',
    'about.innovation': 'Innovation',
    'about.quality': 'Quality',
    'about.customerFocus': 'Customer Focus',
    'about.integrity': 'Integrity',
    'about.customerFirst': 'Customer First',
    'about.customerFirstDesc': 'Every decision we make is centered around our customers\' needs and satisfaction.',
    'about.integrityDesc': 'Honest, transparent, and ethical in all our business practices.',
    'about.sustainability': 'Sustainability',
    'about.sustainabilityDesc': 'Committed to environmental responsibility and sustainable business practices.',
    'about.achievements': 'Our Achievements',
    'about.achievementsSubtitle': 'Numbers that tell our success story',
    'about.team': 'Meet Our Team',
    'about.teamSubtitle': 'The passionate individuals behind our success',
    'about.journey': 'Our Journey',
    'about.journeySubtitle': 'Key milestones in our growth story',
    'about.cta.title': 'Ready to Transform Your Business?',
    'about.cta.subtitle': 'Join thousands of successful businesses that trust us with their e-commerce success',
    'about.cta.getStarted': 'Get Started Today',
    'about.cta.exploreServices': 'Explore Our Services',
    'about.milestones.founded': 'Company Founded',
    'about.milestones.foundedDesc': 'Started with a vision to revolutionize online shopping',
    'about.milestones.firstCustomers': 'First 1000 Customers',
    'about.milestones.firstCustomersDesc': 'Reached our first major milestone',
    'about.milestones.funding': 'Series A Funding',
    'about.milestones.fundingDesc': 'Secured $5M in funding for expansion',
    'about.milestones.international': 'International Launch',
    'about.milestones.internationalDesc': 'Expanded to 5 new countries',
    'about.milestones.products': '1M+ Products',
    'about.milestones.productsDesc': 'Catalog grew to over 1 million products',
    'about.milestones.marketLeader': 'Market Leader',
    'about.milestones.marketLeaderDesc': 'Became the #1 e-commerce platform in our region',
    'about.achievements.happyCustomers': 'Happy Customers',
    'about.achievements.productsSold': 'Products Sold',
    'about.achievements.supportAvailable': 'Support Available',
    'about.achievements.uptime': 'Uptime',
    'about.achievements.countries': 'Countries',
    'about.achievements.teamMembers': 'Team Members',
    'about.testimonials.alex': 'Alex Thompson',
    'about.testimonials.alexRole': 'Business Owner',
    'about.testimonials.alexContent': 'ShopHub transformed our business. The platform is intuitive and the support team is exceptional.',
    'about.testimonials.maria': 'Maria Garcia',
    'about.testimonials.mariaRole': 'Marketing Director',
    'about.testimonials.mariaContent': 'The analytics and insights provided by ShopHub have been invaluable for our growth strategy.',
    'about.testimonials.james': 'James Wilson',
    'about.testimonials.jamesRole': 'E-commerce Manager',
    'about.testimonials.jamesContent': 'Best platform we\'ve used. Reliable, fast, and constantly improving with new features.',
    'about.team.sarah': 'Sarah Johnson',
    'about.team.sarahRole': 'CEO & Founder',
    'about.team.sarahBio': '10+ years of experience in e-commerce and digital transformation',
    'about.team.michael': 'Michael Chen',
    'about.team.michaelRole': 'CTO',
    'about.team.michaelBio': 'Expert in scalable architecture and emerging technologies',
    'about.team.emily': 'Emily Rodriguez',
    'about.team.emilyRole': 'Head of Design',
    'about.team.emilyBio': 'Award-winning designer with focus on user experience',
    'about.team.david': 'David Kim',
    'about.team.davidRole': 'VP of Operations',
    'about.team.davidBio': 'Operations specialist with global supply chain expertise',
    
    // Services Page
    'services.title': 'Our Services',
    'services.subtitle': 'Comprehensive E-Commerce Solutions',
    'services.description': 'From product listing to customer support, we provide end-to-end solutions for your e-commerce success.',
    
    // Service Details
    'services.productListing.title': 'Product Listing',
    'services.productListing.description': 'Comprehensive product catalog management with advanced categorization',
    'services.productListing.features.unlimited': 'Unlimited products',
    'services.productListing.features.bulk': 'Bulk import/export',
    'services.productListing.features.seo': 'SEO optimization',
    'services.productListing.features.multilang': 'Multi-language support',
    
    'services.orderManagement.title': 'Order Management',
    'services.orderManagement.description': 'Streamlined order processing from cart to delivery with real-time tracking',
    'services.orderManagement.features.automation': 'Order automation',
    'services.orderManagement.features.inventory': 'Inventory sync',
    'services.orderManagement.features.shipping': 'Shipping integration',
    'services.orderManagement.features.notifications': 'Customer notifications',
    
    'services.paymentGateway.title': 'Payment Gateway',
    'services.paymentGateway.description': 'Secure payment processing with multiple payment methods and fraud protection',
    'services.paymentGateway.features.gateways': 'Multiple gateways',
    'services.paymentGateway.features.fraud': 'Fraud detection',
    'services.paymentGateway.features.billing': 'Recurring billing',
    'services.paymentGateway.features.pci': 'PCI compliance',
    
    'services.customerSupport.title': 'Customer Support',
    'services.customerSupport.description': '24/7 customer support with multiple channels and AI-powered assistance',
    'services.customerSupport.features.chat': 'Live chat',
    'services.customerSupport.features.ticket': 'Ticket system',
    'services.customerSupport.features.knowledge': 'Knowledge base',
    'services.customerSupport.features.ai': 'AI chatbot',
    
    'services.shippingDelivery.title': 'Shipping & Delivery',
    'services.shippingDelivery.description': 'End-to-end logistics management with real-time tracking and optimization',
    'services.shippingDelivery.features.carrier': 'Carrier integration',
    'services.shippingDelivery.features.route': 'Route optimization',
    'services.shippingDelivery.features.tracking': 'Delivery tracking',
    'services.shippingDelivery.features.returns': 'Returns management',
    
    'services.analyticsReports.title': 'Analytics & Reports',
    'services.analyticsReports.description': 'Data-driven insights with comprehensive reporting and business intelligence',
    'services.analyticsReports.features.sales': 'Sales analytics',
    'services.analyticsReports.features.insights': 'Customer insights',
    'services.analyticsReports.features.metrics': 'Performance metrics',
    'services.analyticsReports.features.dashboards': 'Custom dashboards',
    
    // Services Page Sections
    'services.hero.title': 'Our Services',
    'services.hero.subtitle': 'Comprehensive E-Commerce Solutions',
    'services.hero.description': 'From product listing to customer support, we provide end-to-end solutions for your e-commerce success.',
    'services.hero.cta': 'Get Started Today',
    'services.hero.learnMore': 'Learn More',
    
    'services.pricing.title': 'Choose Your Plan',
    'services.pricing.subtitle': 'Flexible pricing options to fit your business needs',
    'services.pricing.basic.plan': 'Basic',
    'services.pricing.basic.price': '$99',
    'services.pricing.basic.period': '/month',
    'services.pricing.basic.description': 'Perfect for small businesses starting their e-commerce journey',
    'services.pricing.basic.features': '2 services included, Basic support, Standard features, Email support',
    
    'services.pricing.professional.plan': 'Professional',
    'services.pricing.professional.price': '$299',
    'services.pricing.professional.period': '/month',
    'services.pricing.professional.description': 'Ideal for growing businesses with multiple service needs',
    'services.pricing.professional.features': '4 services included, Priority support, Advanced features, Phone support, Custom integrations',
    
    'services.pricing.enterprise.plan': 'Enterprise',
    'services.pricing.enterprise.price': '$799',
    'services.pricing.enterprise.period': '/month',
    'services.pricing.enterprise.description': 'Complete solution for large-scale operations',
    'services.pricing.enterprise.features': 'All 6 services, 24/7 support, Custom development, Dedicated manager, White-label options',
    
    'services.testimonials.title': 'What Our Clients Say',
    'services.testimonials.subtitle': 'Real feedback from businesses using our comprehensive services',
    'services.testimonials.david.name': 'David Chen',
    'services.testimonials.david.role': 'Operations Director',
    'services.testimonials.david.company': 'TechCorp',
    'services.testimonials.david.content': 'The order management system has reduced our processing time by 60% and eliminated errors completely.',
    
    'services.testimonials.maria.name': 'Maria Garcia',
    'services.testimonials.maria.role': 'E-commerce Manager',
    'services.testimonials.maria.company': 'FashionHub',
    'services.testimonials.maria.content': 'The analytics dashboard gives us insights we never had before. Our conversion rates improved by 40%.',
    
    'services.testimonials.james.name': 'James Wilson',
    'services.testimonials.james.role': 'CEO',
    'services.testimonials.james.company': 'EcoStore',
    'services.testimonials.james.content': 'Customer support integration has transformed our customer satisfaction scores from 3.2 to 4.8.',
    
    'services.stats.title': 'Why Choose Us',
    'services.stats.subtitle': 'Numbers that speak for themselves',
    'services.stats.businesses.number': '500+',
    'services.stats.businesses.label': 'Businesses Served',
    'services.stats.uptime.number': '99.9%',
    'services.stats.uptime.label': 'Uptime',
    'services.stats.support.number': '24/7',
    'services.stats.support.label': 'Support Available',
    'services.stats.orders.number': '50M+',
    'services.stats.orders.label': 'Orders Processed',
    
    // How It Works Section
    'services.howItWorks.step': 'Step',
    
    // Contact Page
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Get in Touch',
    'contact.description': 'Ready to transform your e-commerce business? Contact us today for a free consultation.',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email Address',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Message',
    'contact.form.submit': 'Send Message',
    'contact.info.address': 'Address',
    'contact.info.phone': 'Phone',
    'contact.info.email': 'Email',
    
    // Blog Page
    'blog.title': 'Latest Insights',
    'blog.subtitle': 'E-Commerce Trends & Tips',
    'blog.readMore': 'Read More',
    'blog.backToBlog': 'Back to Blog',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome back',
    'dashboard.stats': 'Statistics',
    'dashboard.recentOrders': 'Recent Orders',
    'dashboard.topProducts': 'Top Products',
    'dashboard.quickActions': 'Quick Actions',
    
    // Footer
    'footer.description': 'Empowering e-commerce success with innovative solutions and exceptional support.',
    'footer.quickLinks': 'Quick Links',
    'footer.services': 'Services',
    'footer.company': 'Company',
    'footer.support': 'Support',
    'footer.newsletter': 'Newsletter',
    'footer.newsletterPlaceholder': 'Enter your email',
    'footer.newsletterSubscribe': 'Subscribe',
    'footer.copyright': '© 2024 Stackly24. All rights reserved.',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'An error occurred',
    'common.success': 'Success!',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'delete': 'Delete',
    'common.view': 'View',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.pleaseLogin': 'Please login to access this page',
    'common.mainMenu': 'Main menu',
    'common.selectLanguage': 'Select language',
    'common.ecommerceLogo': 'E-Commerce Logo',
    'common.ctaBackground': 'CTA Background',
    'common.googleMap': 'Google Map',
    
    // Home2 Page Sections
    'home2.hero.title': 'Modern E-commerce',
    'home2.hero.subtitle': 'Platform',
    'home2.hero.description': 'Transform your business with our cutting-edge e-commerce solution. Built for speed, security, and scalability.',
    'home2.hero.getStarted': 'Get Started Free',
    'home2.hero.explore': 'Explore',
    'home2.hero.startJourney': 'Start Your Journey',
    'home2.hero.joinThousands': 'Join thousands of successful businesses using ShopHub',
    'home2.hero.noSetupFees': 'No setup fees',
    'home2.hero.freeTrial': '14-day free trial',
    'home2.hero.cancelAnytime': 'Cancel anytime',
    
    // Home2 Hero Features
    'home2.hero.features.lightningFast': 'Lightning Fast',
    'home2.hero.features.lightningFastDesc': 'Built for speed and performance',
    'home2.hero.features.secureReliable': 'Secure & Reliable',
    'home2.hero.features.secureReliableDesc': 'Enterprise-grade security',
    'home2.hero.features.mobileFirst': 'Mobile First',
    'home2.hero.features.mobileFirstDesc': 'Optimized for all devices',
    
    // Home2 Services Section
    'home2.services.title': 'Everything You Need to Succeed',
    'home2.services.subtitle': 'Comprehensive e-commerce solutions designed to grow your business',
    'home2.services.ecommerce.title': 'E-commerce Solutions',
    'home2.services.ecommerce.description': 'Complete online store management',
    'home2.services.ecommerce.feature1': 'Product Catalog',
    'home2.services.ecommerce.feature2': 'Order Processing',
    'home2.services.ecommerce.feature3': 'Payment Gateway',
    'home2.services.analytics.title': 'Analytics & Insights',
    'home2.services.analytics.description': 'Data-driven business decisions',
    'home2.services.analytics.feature1': 'Sales Reports',
    'home2.services.analytics.feature2': 'Customer Analytics',
    'home2.services.analytics.feature3': 'Performance Metrics',
    'home2.services.logistics.title': 'Logistics & Shipping',
    'home2.services.logistics.description': 'Streamlined delivery operations',
    'home2.services.logistics.feature1': 'Inventory Management',
    'home2.services.logistics.feature2': 'Shipping Integration',
    'home2.services.logistics.feature3': 'Tracking Systems',
    'home2.services.payment.title': 'Payment Solutions',
    'home2.services.payment.description': 'Secure payment processing',
    'home2.services.payment.feature1': 'Multiple Gateways',
    'home2.services.payment.feature2': 'Fraud Protection',
    'home2.services.payment.feature3': 'Recurring Billing',
    
    // Home2 Testimonials Section
    'home2.testimonials.title': 'Trusted by Industry Leaders',
    'home2.testimonials.subtitle': 'See what our customers say about their experience with ShopHub',
    'home2.testimonials.alexandra.name': 'Alexandra Chen',
    'home2.testimonials.alexandra.role': 'CEO, TechStart',
    'home2.testimonials.alexandra.content': 'ShopHub transformed our business. We\'ve seen a 300% increase in sales since switching.',
    'home2.testimonials.marcus.name': 'Marcus Rodriguez',
    'home2.testimonials.marcus.role': 'Founder, FashionHub',
    'home2.testimonials.marcus.content': 'The platform is incredibly intuitive. Our team was up and running in just one day.',
    'home2.testimonials.sarah.name': 'Sarah Kim',
    'home2.testimonials.sarah.role': 'Operations Manager, EcoStore',
    'home2.testimonials.sarah.content': 'Customer support is exceptional. They\'ve helped us scale from 100 to 10,000 orders monthly.',
    
    // Home2 Pricing Section
    'home2.pricing.title': 'Simple, Transparent Pricing',
    'home2.pricing.subtitle': 'Choose the plan that fits your business needs. All plans include our core features.',
    'home2.pricing.starter.name': 'Starter',
    'home2.pricing.starter.description': 'Perfect for small businesses',
    'home2.pricing.starter.price': '$29',
    'home2.pricing.starter.period': '/month',
    'home2.pricing.professional.name': 'Professional',
    'home2.pricing.professional.description': 'Ideal for growing businesses',
    'home2.pricing.professional.price': '$79',
    'home2.pricing.professional.period': '/month',
    'home2.pricing.enterprise.name': 'Enterprise',
    'home2.pricing.enterprise.description': 'For large-scale operations',
    'home2.pricing.enterprise.price': '$199',
    'home2.pricing.enterprise.period': '/month',
    'home2.pricing.mostPopular': 'Most Popular',
    'home2.pricing.getStarted': 'Get Started',
    'home2.pricing.choosePlan': 'Choose Plan',
    'home2.pricing.features.upTo100': 'Up to 100 products',
    'home2.pricing.features.upTo1000': 'Up to 1000 products',
    'home2.pricing.features.unlimited': 'Unlimited products',
    'home2.pricing.features.basicAnalytics': 'Basic analytics',
    'home2.pricing.features.advancedAnalytics': 'Advanced analytics',
    'home2.pricing.features.customAnalytics': 'Custom analytics',
    'home2.pricing.features.emailSupport': 'Email support',
    'home2.pricing.features.prioritySupport': 'Priority support',
    'home2.pricing.features.support247': '24/7 support',
    'home2.pricing.features.mobileApp': 'Mobile app',
    'home2.pricing.features.apiAccess': 'API access',
    'home2.pricing.features.customDomain': 'Custom domain',
    'home2.pricing.features.whiteLabel': 'White-label solution',
    'home2.pricing.features.advancedIntegrations': 'Advanced integrations',
    
    // Home2 Stats Section
    'home2.stats.title': 'Shop by the Numbers',
    'home2.stats.subtitle': 'Trusted by businesses worldwide with proven results',
    'home2.stats.productsSold': 'Products Sold',
    'home2.stats.happyCustomers': 'Happy Customers',
    'home2.stats.countriesServed': 'Countries Served',
    'home2.stats.uptimeGuarantee': 'Uptime Guarantee',
    
    // Home2 CTA Section
    'home2.cta.title': 'Ready to Transform Your Business?',
    'home2.cta.subtitle': 'Join thousands of successful businesses that trust ShopHub for their e-commerce success. Start your journey today and discover what\'s possible.',
    'home2.cta.benefits.instantSetup.title': 'Instant Setup',
    'home2.cta.benefits.instantSetup.description': 'Get your store up and running in minutes, not days',
    'home2.cta.benefits.support247.title': '24/7 Support',
    'home2.cta.benefits.support247.description': 'Our expert team is here to help you succeed',
    'home2.cta.benefits.scaleConfidence.title': 'Scale with Confidence',
    'home2.cta.benefits.scaleConfidence.description': 'Built to handle growth from startup to enterprise',
    'home2.cta.knowMore': 'Know More',
    'home2.cta.scheduleDemo': 'Schedule a Demo',
  },
  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.about': 'من نحن',
    'nav.services': 'الخدمات',
    'nav.blog': 'المدونة',
    'nav.contact': 'اتصل بنا',
    'nav.login': 'تسجيل الدخول',
    'nav.dashboard': 'لوحة التحكم',
    'nav.logout': 'تسجيل الخروج',
    'nav.welcome': 'مرحباً',
    'nav.allServices': 'جميع الخدمات',
    'nav.productListing': 'قائمة المنتجات',
    'nav.orderManagement': 'إدارة الطلبات',
    'nav.paymentGateway': 'بوابة الدفع',
    'nav.customerSupport': 'دعم العملاء',
    'nav.shippingDelivery': 'الشحن والتوصيل',
    'nav.analyticsReports': 'التقارير والتحليلات',
    'nav.home1': 'الرئيسية 1',
    'nav.home2': 'الرئيسية 2',
    'language.english': 'English',
    'language.arabic': 'العربية',
    'language.hebrew': 'עברית',
    
    // Hero Section
    'hero.title': 'حوّل عملك التجاري الإلكتروني',
    'hero.subtitle': 'بسط العمليات، عزز المبيعات، وقدم تجارب عملاء استثنائية مع حلولنا الشاملة للتجارة الإلكترونية.',
    'hero.cta': 'ابدأ اليوم',
    'hero.learnMore': 'اعرف المزيد',
    
    // Home1 Page Sections
    'home1.categories.title': 'تسوق حسب الفئة',
    'home1.categories.subtitle': 'استكشف مجموعتنا الواسعة من الفئات واعثر على ما تبحث عنه بالضبط',
    'home1.featuredProducts.title': 'المنتجات المميزة',
    'home1.featuredProducts.subtitle': 'منتجات مختارة بعناية يحبها عملاؤنا أكثر من غيرها',
    'home1.featuredProducts.addToCart': 'أضف إلى السلة',
    'home1.featuredProducts.viewAll': 'عرض جميع المنتجات',
    'home1.featuredProducts.showLess': 'عرض أقل',
    'home1.cart.title': 'سلتك',
    'home1.cart.items': 'عناصر',
    'home1.cart.total': 'المجموع',
    'home1.cart.clearCart': 'إفراغ السلة',
    'home1.cart.checkout': 'إتمام الشراء',
    'home1.cart.addedToCart': 'تمت الإضافة إلى السلة! ✓',
    'home1.stats.title': 'لماذا تختارنا؟',
    'home1.stats.subtitle': 'نحن ملتزمون بتقديم أفضل تجربة تسوق مع منتجات عالية الجودة وخدمة استثنائية',
    'home1.testimonials.title': 'ماذا يقول عملاؤنا',
    'home1.testimonials.subtitle': 'لا تأخذ كلمتنا فقط - استمع من عملائنا الراضين',
    'home1.testimonials.clickToSeeMore': 'انقر لرؤية المزيد',
    'home1.testimonials.purchased': 'تم شراؤه:',
    'home1.testimonials.verifiedBuyer': 'مشتري موثق',
    'home1.testimonials.premiumMember': 'عضو مميز',
    'home1.testimonials.loyalCustomer': 'عميل مخلص',
    'home1.testimonials.weeksAgo': 'أسابيع مضت',
    'home1.testimonials.monthAgo': 'شهر مضى',
    'home1.testimonials.weekAgo': 'أسبوع مضى',
    'home1.testimonials.content1': 'منتجات بجودة مذهلة وتوصيل سريع. هذا الآن متجري الإلكتروني المفضل!',
    'home1.testimonials.content2': 'خدمة العملاء استثنائية ومجموعة المنتجات لا تصدق. أوصي بشدة!',
    'home1.testimonials.content3': 'أنا أتسوق هنا منذ سنوات ولم أشعر بخيبة أمل أبداً. أسعار رائعة وجودة!',
    'home1.testimonials.content4': 'شحن سريع وجودة منتجات ممتازة. سأتسوق هنا بالتأكيد مرة أخرى!',
    'home1.testimonials.sarahJohnson': 'سارة جونسون',
    'home1.testimonials.michaelChen': 'مايكل تشين',
    'home1.testimonials.emilyRodriguez': 'إيميلي رودريغيز',
    'home1.testimonials.davidKim': 'ديفيد كيم',
    'home1.newsletter.title': 'ابق على اطلاع',
    'home1.newsletter.subtitle': 'احصل على وصول حصري للعروض المبكرة، إطلاق المنتجات الجديدة، ونصائح داخلية تُرسل مباشرة إلى صندوق الوارد الخاص بك',
    'home1.newsletter.exclusiveDeals': 'عروض حصرية',
    'home1.newsletter.exclusiveDealsDesc': 'كن أول من يعرف عن المبيعات السريعة والعروض المحدودة الوقت',
    'home1.newsletter.newProducts': 'تنبيهات المنتجات الجديدة',
    'home1.newsletter.newProductsDesc': 'احصل على إشعار عند إطلاقنا منتجات جديدة مثيرة',
    'home1.newsletter.shoppingTips': 'نصائح التسوق',
    'home1.newsletter.shoppingTipsDesc': 'نصائح خبيرة لمساعدتك في اتخاذ أفضل قرارات الشراء',
    'home1.newsletter.emailLabel': 'عنوان البريد الإلكتروني',
    'home1.newsletter.emailPlaceholder': 'أدخل عنوان بريدك الإلكتروني',
    'home1.newsletter.subscribe': 'اشترك الآن',
    'home1.newsletter.success': '🎉 تم الاشتراك بنجاح! مرحباً بك في العائلة!',
    'home1.newsletter.privacy': 'نحن نحترم خصوصيتك. يمكنك إلغاء الاشتراك في أي وقت. لا رسائل مزعجة، أبداً.',
    
    // Home1 Categories and Products
    'home1.categories.electronics': 'الإلكترونيات',
    'home1.categories.fashion': 'الأزياء',
    'home1.categories.homeGarden': 'المنزل والحديقة',
    'home1.categories.sports': 'الرياضة',
    'home1.categories.books': 'الكتب',
    'home1.categories.beauty': 'الجمال',
    
    // Home1 Product Names
    'home1.products.premiumHeadphones': 'سماعات لاسلكية متميزة',
    'home1.products.fitnessWatch': 'ساعة ذكية لللياقة',
    'home1.products.ultraHdCamera': 'كاميرا فائقة الدقة',
    'home1.products.portableSpeaker': 'مكبر صوت محمول',
    'home1.products.gamingLaptop': 'لابتوب للألعاب',
    'home1.products.wirelessEarbuds': 'سماعات أذن لاسلكية',
    'home1.products.smartphone': 'هاتف ذكي',
    'home1.products.monitor4k': 'شاشة 4K',
    
    // Home1 Stats Labels
    'home1.stats.happyCustomers': 'عملاء سعداء',
    'home1.stats.productsSold': 'منتج مباع',
    'home1.stats.support': 'الدعم',
    'home1.stats.satisfactionRate': 'معدل الرضا',
    
    // About Page
    'about.title': 'من نحن',
    'about.subtitle': '',
    'about.description': 'نحن مزود رائد لحلول التجارة الإلكترونية، نساعد الشركات من جميع الأحجام على النجاح في السوق الرقمية.',
    'about.mission': 'مهمتنا',
    'about.missionText': 'تمكين الشركات بأدوات التجارة الإلكترونية المبتكرة التي تدفع النمو ورضا العملاء.',
    'about.vision': 'رؤيتنا',
    'about.visionText': 'أن نكون الشريك الأكثر ثقة لنجاح التجارة الإلكترونية في جميع أنحاء العالم.',
    'about.values': 'قيمنا',
    'about.valuesSubtitle': 'المبادئ التي توجه كل ما نقوم به',
    'about.innovation': 'الابتكار',
    'about.quality': 'الجودة',
    'about.customerFocus': 'تركيز العملاء',
    'about.integrity': 'النزاهة',
    'about.customerFirst': 'العميل أولاً',
    'about.customerFirstDesc': 'كل قرار نتخذه يركز على احتياجات عملائنا ورضاهم.',
    'about.integrityDesc': 'أمين، شفاف، وأخلاقي في جميع ممارساتنا التجارية.',
    'about.sustainability': 'الاستدامة',
    'about.sustainabilityDesc': 'ملتزمون بالمسؤولية البيئية والممارسات التجارية المستدامة.',
    'about.achievements': 'إنجازاتنا',
    'about.achievementsSubtitle': 'أرقام تحكي قصة نجاحنا',
    'about.team': 'تعرف على فريقنا',
    'about.teamSubtitle': 'الأفراد المتحمسون وراء نجاحنا',
    'about.journey': 'رحلتنا',
    'about.journeySubtitle': 'محطات رئيسية في قصة نمونا',
    'about.cta.title': 'مستعد لتحويل عملك؟',
    'about.cta.subtitle': 'انضم إلى آلاف الشركات الناجحة التي تثق بنا لنجاحها في التجارة الإلكترونية',
    'about.cta.getStarted': 'ابدأ اليوم',
    'about.cta.exploreServices': 'استكشف خدماتنا',
    'about.milestones.founded': 'تأسيس الشركة',
    'about.milestones.foundedDesc': 'بدأنا برؤية لثورة التسوق عبر الإنترنت',
    'about.milestones.firstCustomers': 'أول 1000 عميل',
    'about.milestones.firstCustomersDesc': 'وصلنا إلى أول معلم رئيسي',
    'about.milestones.funding': 'تمويل السلسلة أ',
    'about.milestones.fundingDesc': 'حصلنا على 5 ملايين دولار للتمدد',
    'about.milestones.international': 'الإطلاق الدولي',
    'about.milestones.internationalDesc': 'توسعنا إلى 5 دول جديدة',
    'about.milestones.products': 'أكثر من مليون منتج',
    'about.milestones.productsDesc': 'نما الكتالوج إلى أكثر من مليون منتج',
    'about.milestones.marketLeader': 'قائد السوق',
    'about.milestones.marketLeaderDesc': 'أصبحنا المنصة الأولى للتجارة الإلكترونية في منطقتنا',
    'about.achievements.happyCustomers': 'عملاء سعداء',
    'about.achievements.productsSold': 'منتج مباع',
    'about.achievements.supportAvailable': 'دعم متاح',
    'about.achievements.uptime': 'وقت التشغيل',
    'about.achievements.countries': 'دولة',
    'about.achievements.teamMembers': 'عضو فريق',
    'about.testimonials.alex': 'أليكس طومسون',
    'about.testimonials.alexRole': 'صاحب عمل',
    'about.testimonials.alexContent': 'حول ShopHub عملنا. المنصة بديهية وفريق الدعم استثنائي.',
    'about.testimonials.maria': 'ماريا غارسيا',
    'about.testimonials.mariaRole': 'مدير التسويق',
    'about.testimonials.mariaContent': 'التحليلات والرؤى التي يوفرها ShopHub كانت لا تقدر بثمن لاستراتيجية نمونا.',
    'about.testimonials.james': 'جيمس ويلسون',
    'about.testimonials.jamesRole': 'مدير التجارة الإلكترونية',
    'about.testimonials.jamesContent': 'أفضل منصة استخدمناها. موثوقة، سريعة، وتحسن باستمرار بميزات جديدة.',
    'about.team.sarah': 'سارة جونسون',
    'about.team.sarahRole': 'الرئيس التنفيذي والمؤسس',
    'about.team.sarahBio': 'أكثر من 10 سنوات من الخبرة في التجارة الإلكترونية والتحول الرقمي',
    'about.team.michael': 'مايكل تشين',
    'about.team.michaelRole': 'مدير التكنولوجيا',
    'about.team.michaelBio': 'خبير في الهندسة المعمارية القابلة للتطوير والتقنيات الناشئة',
    'about.team.emily': 'إيميلي رودريغيز',
    'about.team.emilyRole': 'رئيس التصميم',
    'about.team.emilyBio': 'مصممة حائزة على جوائز مع التركيز على تجربة المستخدم',
    'about.team.david': 'ديفيد كيم',
    'about.team.davidRole': 'نائب رئيس العمليات',
    'about.team.davidBio': 'متخصص في العمليات مع خبرة في سلسلة التوريد العالمية',
    
    // Services Page
    'services.title': 'خدماتنا',
    'services.subtitle': 'حلول شاملة للتجارة الإلكترونية',
    'services.description': 'من قائمة المنتجات إلى دعم العملاء، نقدم حلولاً شاملة لنجاح تجارتك الإلكترونية.',
    
    // Service Details
    'services.productListing.title': 'قائمة المنتجات',
    'services.productListing.description': 'إدارة كتالوج المنتجات المتكاملة مع تصنيف متقدم',
    'services.productListing.features.unlimited': 'منتجات غير محدودة',
    'services.productListing.features.bulk': 'استيراد/تصدير بكميات كبيرة',
    'services.productListing.features.seo': 'تحسين التسويق الجغرافي',
    'services.productListing.features.multilang': 'دعم اللغات المتعددة',
    
    'services.orderManagement.title': 'إدارة الطلبات',
    'services.orderManagement.description': 'معالجة الطلبات بشكل مبسط مع تتبع حالة الطلب في الوقت الحقيقي',
    'services.orderManagement.features.automation': 'تطوير الطلب',
    'services.orderManagement.features.inventory': 'مزامنة المخزون',
    'services.orderManagement.features.shipping': 'دمج الشحن مع الطلب',
    'services.orderManagement.features.notifications': 'إرسال إشعارات للعملاء',
    
    'services.paymentGateway.title': 'بوابة الدفع',
    'services.paymentGateway.description': 'معالجة دفع آمنة باستخدام عدة طرق الدفع وحماية من الاحتيال',
    'services.paymentGateway.features.gateways': 'عدة بوابات',
    'services.paymentGateway.features.fraud': 'كشف الاحتيال',
    'services.paymentGateway.features.billing': 'فوترة متكررة',
    'services.paymentGateway.features.pci': 'الالتزام بمعايير PCI',
    
    'services.customerSupport.title': 'دعم العملاء',
    'services.customerSupport.description': 'دعم 24/7 مع عدة قنوات ومساعدة آلية',
    'services.customerSupport.features.chat': 'الدردشة المباشرة',
    'services.customerSupport.features.ticket': 'نظام التذاكر',
    'services.customerSupport.features.knowledge': 'قاعدة المعرفة',
    'services.customerSupport.features.ai': 'روبوت الدردشة الآلي',
    
    'services.shippingDelivery.title': 'الشحن والتوصيل',
    'services.shippingDelivery.description': 'إدارة اللوجستية المبسطة مع تتبع حالة الشحن في الوقت الحقيقي وتحسين الأداء',
    'services.shippingDelivery.features.carrier': 'دمج الشحن مع الطلب',
    'services.shippingDelivery.features.route': 'تحسين المسار',
    'services.shippingDelivery.features.tracking': 'تتبع الشحن',
    'services.shippingDelivery.features.returns': 'إدارة الإرجاع',
    
    'services.analyticsReports.title': 'التقارير والتحليلات',
    'services.analyticsReports.description': 'المعلومات المستندة إلى البيانات مع تقارير متكاملة وإدارة الأعمال',
    'services.analyticsReports.features.sales': 'تحليل المبيعات',
    'services.analyticsReports.features.insights': 'معلومات العملاء',
    'services.analyticsReports.features.metrics': 'مقاييس الأداء',
    'services.analyticsReports.features.dashboards': 'لوحات تحليلية خاصة',
    
    // Services Page Sections
    'services.hero.title': 'خدماتنا',
    'services.hero.subtitle': 'حلول شاملة للتجارة الإلكترونية',
    'services.hero.description': 'من قائمة المنتجات إلى دعم العملاء، نقدم حلولاً شاملة لنجاح تجارتك الإلكترونية.',
    'services.hero.cta': 'ابدأ اليوم',
    'services.hero.learnMore': 'اعرف المزيد',
    
    'services.pricing.title': 'اختيار الخطة',
    'services.pricing.subtitle': 'خيارات سعرية مرنة لتناسب احتياجات عملك',
    'services.pricing.basic.plan': 'الأساسي',
    'services.pricing.basic.price': '99$',
    'services.pricing.basic.period': '/شهر',
    'services.pricing.basic.description': 'مثالية للشركات الصغيرة تبدأ رحلتها في التجارة الإلكترونية',
    'services.pricing.basic.features': '2 خدمات متضمنة, دعم أساسي, ميزات معيارية, دعم بالبريد الإلكتروني',
    
    'services.pricing.professional.plan': 'المهني',
    'services.pricing.professional.price': '299$',
    'services.pricing.professional.period': '/شهر',
    'services.pricing.professional.description': 'مثالية للشركات النامية تحتاج خدمات متعددة',
    'services.pricing.professional.features': '4 خدمات متضمنة, دعم ذو أولوية, ميزات متقدمة, دعم بالهاتف, تكاملات مخصصة',
    
    'services.pricing.enterprise.plan': 'المؤسسة',
    'services.pricing.enterprise.price': '799$',
    'services.pricing.enterprise.period': '/شهر',
    'services.pricing.enterprise.description': 'حل كامل للعمليات الكبيرة',
    'services.pricing.enterprise.features': 'جميع 6 خدمات, دعم 24/7, تطوير مخصص, مدير مخصص, خيارات علامة بيضاء',
    
    'services.testimonials.title': 'ما يقول عملاؤنا',
    'services.testimonials.subtitle': 'تعليقات حقيقية من الشركات التي تستخدم خدماتنا الشاملة',
    'services.testimonials.david.name': 'ديفيد تشين',
    'services.testimonials.david.role': 'مدير العمليات',
    'services.testimonials.david.company': 'تك تورب',
    'services.testimonials.david.content': 'نظام إدارة الطلبات قد خفض وقت المعالجة 60% وأزال الأخطاء تماماً.',
    
    'services.testimonials.maria.name': 'ماريا غارسيا',
    'services.testimonials.maria.role': 'مدير التسويق',
    'services.testimonials.maria.company': 'فاشن هب',
    'services.testimonials.maria.content': 'لوحة التحليلات تعطينا معلومات لم نمتلكها من قبل. معدل التحويل ارتفع بنسبة 40%.',
    
    'services.testimonials.james.name': 'جيمس ويلسون',
    'services.testimonials.james.role': 'الرئيس التنفيذي',
    'services.testimonials.james.company': 'إيكو ستور',
    'services.testimonials.james.content': 'دمج تكامل الدعم العملائي قد أغير معدل أرضا العملاء من 3.2 إلى 4.8.',
    
    'services.stats.title': 'لماذا نحن؟',
    'services.stats.subtitle': 'الأرقام تتحدث لنفسها',
    'services.stats.businesses.number': '500+',
    'services.stats.businesses.label': 'الشركات المدعومة',
    'services.stats.uptime.number': '99.9%',
    'services.stats.uptime.label': 'وقت التشغيل',
    'services.stats.support.number': '24/7',
    'services.stats.support.label': 'دعم متاح',
    'services.stats.orders.number': '50M+',
    'services.stats.orders.label': 'الطلبات المعالجة',
    
    // How It Works Section
    'services.howItWorks.step': 'خطوة',
    
    // Contact Page
    'contact.title': 'اتصل بنا',
    'contact.subtitle': 'تواصل معنا',
    'contact.description': 'مستعد لتحويل عملك التجاري الإلكتروني؟ اتصل بنا اليوم للحصول على استشارة مجانية.',
    'contact.form.name': 'الاسم الكامل',
    'contact.form.email': 'عنوان البريد الإلكتروني',
    'contact.form.subject': 'الموضوع',
    'contact.form.message': 'الرسالة',
    'contact.form.submit': 'إرسال الرسالة',
    'contact.info.address': 'العنوان',
    'contact.info.phone': 'الهاتف',
    'contact.info.email': 'البريد الإلكتروني',
    
    // Blog Page
    'blog.title': 'أحدث الرؤى',
    'blog.subtitle': 'اتجاهات ونصائح التجارة الإلكترونية',
    'blog.readMore': 'اقرأ المزيد',
    'blog.backToBlog': 'العودة إلى المدونة',
    
    // Dashboard
    'dashboard.title': 'لوحة التحكم',
    'dashboard.welcome': 'مرحباً بعودتك',
    'dashboard.stats': 'الإحصائيات',
    'dashboard.recentOrders': 'الطلبات الحديثة',
    'dashboard.topProducts': 'أفضل المنتجات',
    'dashboard.quickActions': 'إجراءات سريعة',
    
    // Footer
    'footer.description': 'تمكين نجاح التجارة الإلكترونية بحلول مبتكرة ودعم استثنائي.',
    'footer.quickLinks': 'روابط سريعة',
    'footer.services': 'الخدمات',
    'footer.company': 'الشركة',
    'footer.support': 'الدعم',
    'footer.newsletter': 'النشرة الإخبارية',
    'footer.newsletterPlaceholder': 'أدخل بريدك الإلكتروني',
    'footer.newsletterSubscribe': 'اشتراك',
    'footer.copyright': '© 2024 ستاكلي 24. جميع الحقوق محفوظة.',
    
    // Common
    'common.loading': 'جاري التحميل...',
    'common.error': 'حدث خطأ',
    'common.success': 'نجح!',
    'common.cancel': 'إلغاء',
    'common.save': 'حفظ',
    'common.edit': 'تعديل',
    'delete': 'حذف',
    'common.view': 'عرض',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    'common.previous': 'السابق',
    'common.pleaseLogin': 'يرجى تسجيل الدخول للوصول إلى هذه الصفحة',
    'common.mainMenu': 'القائمة الرئيسية',
    'common.selectLanguage': 'اختر اللغة',
    'common.ecommerceLogo': 'شعار التجارة الإلكترونية',
    'common.ctaBackground': 'خلفية دعوة للعمل',
    'common.googleMap': 'خريطة جوجل',
    
    // Home2 Page Sections
    'home2.hero.title': 'منصة التجارة الإلكترونية',
    'home2.hero.subtitle': 'الحديثة',
    'home2.hero.description': 'حوّل عملك بحلولنا المتطورة للتجارة الإلكترونية. مصممة للسرعة والأمان وقابلية التوسع.',
    'home2.hero.getStarted': 'ابدأ مجاناً',
    'home2.hero.explore': 'استكشف',
    'home2.hero.startJourney': 'ابدأ رحلتك',
    'home2.hero.joinThousands': 'انضم إلى آلاف الشركات الناجحة التي تستخدم شوب هب',
    'home2.hero.noSetupFees': 'لا رسوم إعداد',
    'home2.hero.freeTrial': 'تجربة مجانية لمدة 14 يوماً',
    'home2.hero.cancelAnytime': 'إلغاء في أي وقت',
    
    // Home2 Hero Features
    'home2.hero.features.lightningFast': 'سريع كالبرق',
    'home2.hero.features.lightningFastDesc': 'مصمم للسرعة والأداء',
    'home2.hero.features.secureReliable': 'آمن وموثوق',
    'home2.hero.features.secureReliableDesc': 'أمان على مستوى المؤسسات',
    'home2.hero.features.mobileFirst': 'أولوية للهاتف المحمول',
    'home2.hero.features.mobileFirstDesc': 'محسن لجميع الأجهزة',
    
    // Home2 Services Section
    'home2.services.title': 'كل ما تحتاجه للنجاح',
    'home2.services.subtitle': 'حلول شاملة للتجارة الإلكترونية مصممة لتنمية عملك',
    'home2.services.ecommerce.title': 'حلول التجارة الإلكترونية',
    'home2.services.ecommerce.description': 'إدارة متجر إلكتروني متكامل',
    'home2.services.ecommerce.feature1': 'كتالوج المنتجات',
    'home2.services.ecommerce.feature2': 'معالجة الطلبات',
    'home2.services.ecommerce.feature3': 'بوابة الدفع',
    'home2.services.analytics.title': 'التحليلات والرؤى',
    'home2.services.analytics.description': 'قرارات تجارية مدعومة بالبيانات',
    'home2.services.analytics.feature1': 'تقارير المبيعات',
    'home2.services.analytics.feature2': 'تحليل العملاء',
    'home2.services.analytics.feature3': 'مقاييس الأداء',
    'home2.services.logistics.title': 'الخدمات اللوجستية والشحن',
    'home2.services.logistics.description': 'عمليات توصيل مبسطة',
    'home2.services.logistics.feature1': 'إدارة المخزون',
    'home2.services.logistics.feature2': 'تكامل الشحن',
    'home2.services.logistics.feature3': 'أنظمة التتبع',
    'home2.services.payment.title': 'حلول الدفع',
    'home2.services.payment.description': 'معالجة دفع آمنة',
    'home2.services.payment.feature1': 'بوابات متعددة',
    'home2.services.payment.feature2': 'حماية من الاحتيال',
    'home2.services.payment.feature3': 'فوترة متكررة',
    
    // Home2 Testimonials Section
    'home2.testimonials.title': 'موثوق به من قادة الصناعة',
    'home2.testimonials.subtitle': 'شاهد ما يقوله عملاؤنا عن تجربتهم مع شوب هب',
    'home2.testimonials.alexandra.name': 'ألكسندرا تشين',
    'home2.testimonials.alexandra.role': 'الرئيس التنفيذي، تيك ستارت',
    'home2.testimonials.alexandra.content': 'حوّل شوب هب عملنا. لقد شهدنا زيادة بنسبة 300% في المبيعات منذ التحويل.',
    'home2.testimonials.marcus.name': 'ماركوس رودريغيز',
    'home2.testimonials.marcus.role': 'مؤسس، فاشن هب',
    'home2.testimonials.marcus.content': 'المنصة بديهية بشكل لا يصدق. كان فريقنا يعمل في يوم واحد فقط.',
    'home2.testimonials.sarah.name': 'سارة كيم',
    'home2.testimonials.sarah.role': 'مديرة العمليات، إيكو ستور',
    'home2.testimonials.sarah.content': 'دعم العملاء استثنائي. لقد ساعدونا في التوسع من 100 إلى 10,000 طلب شهرياً.',
    
    // Home2 Pricing Section
    'home2.pricing.title': 'أسعار بسيطة وشفافة',
    'home2.pricing.subtitle': 'اختر الخطة التي تناسب احتياجات عملك. جميع الخطط تتضمن ميزاتنا الأساسية.',
    'home2.pricing.starter.name': 'البداية',
    'home2.pricing.starter.description': 'مثالية للشركات الصغيرة',
    'home2.pricing.starter.price': '29$',
    'home2.pricing.starter.period': '/شهر',
    'home2.pricing.professional.name': 'المهني',
    'home2.pricing.professional.description': 'مثالية للشركات النامية',
    'home2.pricing.professional.price': '79$',
    'home2.pricing.professional.period': '/شهر',
    'home2.pricing.enterprise.name': 'المؤسسة',
    'home2.pricing.enterprise.description': 'للعمليات واسعة النطاق',
    'home2.pricing.enterprise.price': '199$',
    'home2.pricing.enterprise.period': '/شهر',
    'home2.pricing.mostPopular': 'الأكثر شعبية',
    'home2.pricing.getStarted': 'ابدأ الآن',
    'home2.pricing.choosePlan': 'اختر الخطة',
    'home2.pricing.features.upTo100': 'حتى 100 منتج',
    'home2.pricing.features.upTo1000': 'حتى 1000 منتج',
    'home2.pricing.features.unlimited': 'منتجات غير محدودة',
    'home2.pricing.features.basicAnalytics': 'تحليلات أساسية',
    'home2.pricing.features.advancedAnalytics': 'تحليلات متقدمة',
    'home2.pricing.features.customAnalytics': 'تحليلات مخصصة',
    'home2.pricing.features.emailSupport': 'دعم عبر البريد الإلكتروني',
    'home2.pricing.features.prioritySupport': 'دعم ذو أولوية',
    'home2.pricing.features.support247': 'دعم 24/7',
    'home2.pricing.features.mobileApp': 'تطبيق الهاتف المحمول',
    'home2.pricing.features.apiAccess': 'الوصول إلى API',
    'home2.pricing.features.customDomain': 'نطاق مخصص',
    'home2.pricing.features.whiteLabel': 'حل العلامة البيضاء',
    'home2.pricing.features.advancedIntegrations': 'تكاملات متقدمة',
    
    // Home2 Stats Section
    'home2.stats.title': 'شوب بالأرقام',
    'home2.stats.subtitle': 'موثوق به من الشركات في جميع أنحاء العالم مع نتائج مثبتة',
    'home2.stats.productsSold': 'منتج تم بيعه',
    'home2.stats.happyCustomers': 'عميل سعيد',
    'home2.stats.countriesServed': 'بلد تم خدمته',
    'home2.stats.uptimeGuarantee': 'ضمان وقت التشغيل',
    
    // Home2 CTA Section
    'home2.cta.title': 'مستعد لتحويل عملك؟',
    'home2.cta.subtitle': 'انضم إلى آلاف الشركات الناجحة التي تثق بشوب هب لنجاحها في التجارة الإلكترونية. ابدأ رحلتك اليوم واكتشف ما هو ممكن.',
    'home2.cta.benefits.instantSetup.title': 'إعداد فوري',
    'home2.cta.benefits.instantSetup.description': 'احصل على متجرك يعمل في دقائق، وليس أيام',
    'home2.cta.benefits.support247.title': 'دعم 24/7',
    'home2.cta.benefits.support247.description': 'فريقنا الخبير هنا لمساعدتك على النجاح',
    'home2.cta.benefits.scaleConfidence.title': 'توسع بثقة',
    'home2.cta.benefits.scaleConfidence.description': 'مصمم للتعامل مع النمو من الشركة الناشئة إلى المؤسسة',
    'home2.cta.knowMore': 'اعرف المزيد',
    'home2.cta.scheduleDemo': 'جدولة عرض توضيحي',
  },
  he: {
    // Navigation
    'nav.home': 'בית',
    'nav.about': 'אודות',
    'nav.services': 'שירותים',
    'nav.blog': 'בלוג',
    'nav.contact': 'צור קשר',
    'nav.login': 'התחברות',
    'nav.dashboard': 'לוח בקרה',
    'nav.logout': 'התנתקות',
    'nav.welcome': 'ברוכים הבאים',
    'nav.allServices': 'כל השירותים',
    'nav.productListing': 'רשימת מוצרים',
    'nav.orderManagement': 'ניהול הזמנות',
    'nav.paymentGateway': 'שער תשלום',
    'nav.customerSupport': 'תמיכת לקוחות',
    'nav.shippingDelivery': 'משלוח ואספקה',
    'nav.analyticsReports': 'דוחות וניתוח',
    'nav.home1': 'בית 1',
    'nav.home2': 'בית 2',
    'language.english': 'English',
    'language.arabic': 'العربية',
    'language.hebrew': 'עברית',
    
    // Hero Section
    'hero.title': 'שנה את עסק המסחר האלקטרוני שלך',
    'hero.subtitle': 'פשט פעולות, הגבר מכירות, וספק חוויות לקוח יוצאות דופן עם פתרונות המסחר האלקטרוני המקיפים שלנו.',
    'hero.cta': 'התחל היום',
    'hero.learnMore': 'למידע נוסף',
    
    // Home1 Page Sections
    'home1.categories.title': 'קנה לפי קטגוריה',
    'home1.categories.subtitle': 'חקור את טווח הקטגוריות הרחב שלנו ומצא בדיוק מה שאתה מחפש',
    'home1.featuredProducts.title': 'מוצרים מובילים',
    'home1.featuredProducts.subtitle': 'מוצרים נבחרים בקפידה שהלקוחות שלנו אוהבים הכי הרבה',
    'home1.featuredProducts.addToCart': 'הוסף לעגלה',
    'home1.featuredProducts.viewAll': 'הצג את כל המוצרים',
    'home1.featuredProducts.showLess': 'הצג פחות',
    'home1.cart.title': 'העגלה שלך',
    'home1.cart.items': 'פריטים',
    'home1.cart.total': 'סה"כ',
    'home1.cart.clearCart': 'נקה עגלה',
    'home1.cart.checkout': 'תשלום',
    'home1.cart.addedToCart': 'נוסף לעגלה! ✓',
    'home1.stats.title': 'למה לבחור בנו?',
    'home1.stats.subtitle': 'אנחנו מחויבים לספק את חוויית הקנייה הטובה ביותר עם מוצרים באיכות גבוהה ושירות יוצא דופן',
    'home1.testimonials.title': 'מה הלקוחות שלנו אומרים',
    'home1.testimonials.subtitle': 'אל תקח רק את המילה שלנו - שמע מהלקוחות המרוצים שלנו',
    'home1.testimonials.clickToSeeMore': 'לחץ לראות עוד',
    'home1.testimonials.purchased': 'נרכש:',
    'home1.testimonials.verifiedBuyer': 'קונה מאומת',
    'home1.testimonials.premiumMember': 'חבר פרימיום',
    'home1.testimonials.loyalCustomer': 'לקוח נאמן',
    'home1.testimonials.weeksAgo': 'שבועות לפני',
    'home1.testimonials.monthAgo': 'חודש לפני',
    'home1.testimonials.weekAgo': 'שבוע לפני',
    'home1.testimonials.content1': 'מוצרים באיכות מדהימה ומשלוח מהיר. זה עכשיו החנות המקוונת המועדפת עלי!',
    'home1.testimonials.content2': 'שירות הלקוחות יוצא דופן ומגוון המוצרים מדהים. מומלץ מאוד!',
    'home1.testimonials.content3': 'אני קונה כאן שנים ומעולם לא התאכזבתי. מחירים נהדרים ואיכות!',
    'home1.testimonials.content4': 'משלוח מהיר ואיכות מוצרים מעולה. בהחלט אקנה כאן שוב!',
    'home1.testimonials.sarahJohnson': 'שרה ג\'ונסון',
    'home1.testimonials.michaelChen': 'מייקל צ\'ן',
    'home1.testimonials.emilyRodriguez': 'אמילי רודריגז',
    'home1.testimonials.davidKim': 'דוד קים',
    'home1.newsletter.title': 'הישאר מעודכן',
    'home1.newsletter.subtitle': 'קבל גישה בלעדית למבצעים מוקדמים, השקות מוצרים חדשים וטיפים פנימיים שנשלחים ישירות לתיבת הדואר שלך',
    'home1.newsletter.exclusiveDeals': 'מבצעים בלעדיים',
    'home1.newsletter.exclusiveDealsDesc': 'היה הראשון לדעת על מבצעים מהירים והצעות מוגבלות זמן',
    'home1.newsletter.newProducts': 'התראות מוצרים חדשים',
    'home1.newsletter.newProductsDesc': 'קבל הודעה כשאנחנו משקיעים מוצרים חדשים מרגשים',
    'home1.newsletter.shoppingTips': 'טיפים לקנייה',
    'home1.newsletter.shoppingTipsDesc': 'ייעוץ מומחים שיעזור לך לקבל את החלטות הקנייה הטובות ביותר',
    'home1.newsletter.emailLabel': 'כתובת דוא"ל',
    'home1.newsletter.emailPlaceholder': 'הזן את כתובת הדוא"ל שלך',
    'home1.newsletter.subscribe': 'הירשם עכשיו',
    'home1.newsletter.success': '🎉 נרשמת בהצלחה! ברוך הבא למשפחה!',
    'home1.newsletter.privacy': 'אנחנו מכבדים את הפרטיות שלך. בטל הרשמה בכל עת. לא ספאם, לעולם לא.',
    
    // Home1 Categories and Products
    'home1.categories.electronics': 'אלקטרוניקה',
    'home1.categories.fashion': 'אופנה',
    'home1.categories.homeGarden': 'בית וגן',
    'home1.categories.sports': 'ספורט',
    'home1.categories.books': 'ספרים',
    'home1.categories.beauty': 'יופי',
    
    // Home1 Product Names
    'home1.products.premiumHeadphones': 'אוזניות אלחוטיות פרימיום',
    'home1.products.fitnessWatch': 'שעון חכם לכושר',
    'home1.products.ultraHdCamera': 'מצלמה אולטרה HD',
    'home1.products.portableSpeaker': 'רמקול נייד',
    'home1.products.gamingLaptop': 'מחשב נייד למשחקים',
    'home1.products.wirelessEarbuds': 'אוזניות אלחוטיות',
    'home1.products.smartphone': 'טלפון חכם',
    'home1.products.monitor4k': 'מסך 4K',
    
    // Home1 Stats Labels
    'home1.stats.happyCustomers': 'לקוחות מרוצים',
    'home1.stats.productsSold': 'מוצרים נמכרו',
    'home1.stats.support': 'תמיכה',
    'home1.stats.satisfactionRate': 'שיעור שביעות רצון',
    
    // About Page
    'about.title': 'אודותינו',
    'about.subtitle': '',
    'about.description': 'אנחנו ספק מוביל של פתרונות מסחר אלקטרוני, עוזרים לעסקים מכל הגדלים להצליח בשוק הדיגיטלי.',
    'about.mission': 'המשימה שלנו',
    'about.missionText': 'לאפשר לעסקים כלים חדשניים למסחר אלקטרוני שמניעים צמיחה ושביעות רצון לקוחות.',
    'about.vision': 'החזון שלנו',
    'about.visionText': 'להיות השותף המהימן ביותר להצלחת מסחר אלקטרוני ברחבי העולם.',
    'about.values': 'הערכים שלנו',
    'about.valuesSubtitle': 'העקרונות שמנחים כל מה שאנחנו עושים',
    'about.innovation': 'חדשנות',
    'about.quality': 'איכות',
    'about.customerFocus': 'מיקוד לקוחות',
    'about.integrity': 'יושרה',
    'about.customerFirst': 'הלקוח קודם',
    'about.customerFirstDesc': 'כל החלטה שאנחנו מקבלים מתמקדת בצרכים של הלקוחות שלנו ובשביעות רצונם.',
    'about.integrityDesc': 'ישרים, שקופים ואתיים בכל הפרקטיקות העסקיות שלנו.',
    'about.sustainability': 'קיימות',
    'about.sustainabilityDesc': 'מחויבים לאחריות סביבתית ופרקטיקות עסקיות בר-קיימא.',
    'about.achievements': 'ההישגים שלנו',
    'about.achievementsSubtitle': 'מספרים שמספרים את סיפור ההצלחה שלנו',
    'about.team': 'פגוש את הצוות שלנו',
    'about.teamSubtitle': 'האנשים המסורים מאחורי ההצלחה שלנו',
    'about.journey': 'המסע שלנו',
    'about.journeySubtitle': 'אבני דרך מרכזיות בסיפור הצמיחה שלנו',
    'about.cta.title': 'מוכן לשנות את העסק שלך?',
    'about.cta.subtitle': 'הצטרף לאלפי עסקים מצליחים שסומכים עלינו להצלחת המסחר האלקטרוני שלהם',
    'about.cta.getStarted': 'התחל היום',
    'about.cta.exploreServices': 'חקור את השירותים שלנו',
    'about.milestones.founded': 'החברה נוסדה',
    'about.milestones.foundedDesc': 'התחלנו עם חזון למהפכה בקניות מקוונות',
    'about.milestones.firstCustomers': '1000 הלקוחות הראשונים',
    'about.milestones.firstCustomersDesc': 'הגענו לאבן הדרך הראשונה שלנו',
    'about.milestones.funding': 'מימון סדרה א',
    'about.milestones.fundingDesc': 'השגנו 5 מיליון דולר להרחבה',
    'about.milestones.international': 'השקה בינלאומית',
    'about.milestones.internationalDesc': 'הרחבנו ל-5 מדינות חדשות',
    'about.milestones.products': 'יותר ממיליון מוצרים',
    'about.milestones.productsDesc': 'הקטלוג גדל ליותר ממיליון מוצרים',
    'about.milestones.marketLeader': 'מוביל השוק',
    'about.milestones.marketLeaderDesc': 'הפכנו לפלטפורמת המסחר האלקטרוני מספר 1 באזור שלנו',
    'about.achievements.happyCustomers': 'לקוחות מרוצים',
    'about.achievements.productsSold': 'מוצרים נמכרו',
    'about.achievements.supportAvailable': 'תמיכה זמינה',
    'about.achievements.uptime': 'זמן פעילות',
    'about.achievements.countries': 'מדינות',
    'about.achievements.teamMembers': 'חברי צוות',
    'about.testimonials.alex': 'אלכס תומפסון',
    'about.testimonials.alexRole': 'בעל עסק',
    'about.testimonials.alexContent': 'ShopHub שינה את העסק שלנו. הפלטפורמה אינטואיטיבית וצוות התמיכה יוצא דופן.',
    'about.testimonials.maria': 'מריה גרסיה',
    'about.testimonials.mariaRole': 'מנהלת שיווק',
    'about.testimonials.mariaContent': 'הניתוחים והתובנות שסיפק ShopHub היו יקרי ערך לאסטרטגיית הצמיחה שלנו.',
    'about.testimonials.james': 'ג\'יימס וילסון',
    'about.testimonials.jamesRole': 'מנהל מסחר אלקטרוני',
    'about.testimonials.jamesContent': 'הפלטפורמה הטובה ביותרתמשנו בה. אמינה, מהירה ומשתפרת ללא הרף עם תכונות חדשות.',
    'about.team.sarah': 'שרה ג\'ונסון',
    'about.team.sarahRole': 'מנכ"ל ומקים',
    'about.team.sarahBio': 'יותר מ-10 שנות ניסיון במסחר אלקטרוני וטרנספורמציה דיגיטלית',
    'about.team.michael': 'מייקל צ\'ן',
    'about.team.michaelRole': 'מנהל טכנולוגיה',
    'about.team.michaelBio': 'מומחה בארכיטקטורה ניתנת להרחבה וטכנולוגיות מתפתחות',
    'about.team.emily': 'אמילי רודריגז',
    'about.team.emilyRole': 'ראש עיצוב',
    'about.team.emilyBio': 'מעצבת זוכת פרסים עם דגש על חוויית משתמש',
    'about.team.david': 'דוד קים',
    'about.team.davidRole': 'סמנכ"ל פעולות',
    'about.team.davidBio': 'מומחה פעולות עם ניסיון בשרשרת אספקה גלובלית',
    
    // Services Page
    'services.title': 'השירותים שלנו',
    'services.subtitle': 'פתרונות מקיפים למסחר אלקטרוני',
    'services.description': 'מרשימת מוצרים ועד תמיכת לקוחות, אנו מספקים פתרונות מקיפים להצלחת המסחר האלקטרוני שלך.',
    
    // Service Details
    'services.productListing.title': 'רשימת מוצרים',
    'services.productListing.description': 'ניהול מסגר מוצרים מלא עם טכניקת סיווג מתקדמת',
    'services.productListing.features.unlimited': 'מוצרים ללא הגבלה',
    'services.productListing.features.bulk': 'הוספה/הסרה בכמויות גדולות',
    'services.productListing.features.seo': 'אופטימיזציה חיצונית',
    'services.productListing.features.multilang': 'תמיכה בשפות מרובות',
    
    'services.orderManagement.title': 'ניהול הזמנות',
    'services.orderManagement.description': 'ניהול מסגר מוצרים מלא עם טכניקת סיווג מתקדמת',
    'services.orderManagement.features.automation': 'אוטומציה מסגר',
    'services.orderManagement.features.inventory': 'הסנס מסגר',
    'services.orderManagement.features.shipping': 'הסנס מסגר',
    'services.orderManagement.features.notifications': 'הודעות לקוחות',
    
    'services.paymentGateway.title': 'שער תשלום',
    'services.paymentGateway.description': 'מעבדה מאובטחת של תשלום עם מספר מסלות והגנה מפני הונאה',
    'services.paymentGateway.features.gateways': 'מספר מסלות',
    'services.paymentGateway.features.fraud': 'גילוי אובדן',
    'services.paymentGateway.features.billing': 'חיוב מחזורי',
    'services.paymentGateway.features.pci': 'התאמה למדיניות PCI',
    
    'services.customerSupport.title': 'תמיכת לקוחות',
    'services.customerSupport.description': 'תמיכה 24/7 עם מספר מסלות ועזרה מחשבית',
    'services.customerSupport.features.chat': 'הדרדר מהיר',
    'services.customerSupport.features.ticket': 'מערכת תקלות',
    'services.customerSupport.features.knowledge': 'מסד מידע',
    'services.customerSupport.features.ai': 'אטומט דרדר',
    
    'services.shippingDelivery.title': 'משלוח ואספקה',
    'services.shippingDelivery.description': 'ניהול לוגיסטיקה מלא עם טכניקת סיווג מתקדמת',
    'services.shippingDelivery.features.carrier': 'הסנס מסגר',
    'services.shippingDelivery.features.route': 'הסנס מסגר',
    'services.shippingDelivery.features.tracking': 'הסנס מסגר',
    'services.shippingDelivery.features.returns': 'ניהול מסגר',
    
    'services.analyticsReports.title': 'ניתוח ותובנות',
    'services.analyticsReports.description': 'מידע מבוסס נתונים עם טכניקת סיווג מתקדמת',
    'services.analyticsReports.features.sales': 'ניתוח מכירות',
    'services.analyticsReports.features.insights': 'מידע לקוחות',
    'services.analyticsReports.features.metrics': 'מדדי ביצוע',
    'services.analyticsReports.features.dashboards': 'לוחות מניות מותאמים',
    
    // Services Page Sections
    'services.hero.title': 'השירותים שלנו',
    'services.hero.subtitle': 'פתרונות מקיפים למסחר אלקטרוני',
    'services.hero.description': 'מרשימת מוצרים ועד תמיכת לקוחות, אנו מספקים פתרונות מקיפים להצלחת המסחר האלקטרוני שלך.',
    'services.hero.cta': 'התחל היום',
    'services.hero.learnMore': 'למידע נוסף',
    
    'services.pricing.title': 'בחר את התוכנית שמתאימה לצרכי העסק שלך',
    'services.pricing.subtitle': 'אפשרויות מחיר מודלניות להתאמה לצרכי העסק שלך',
    'services.pricing.basic.plan': 'בסיסי',
    'services.pricing.basic.price': '99$',
    'services.pricing.basic.period': '/חודש',
    'services.pricing.basic.description': 'מושלם לעסקים קטנים שמתחילים את דרכם במסחר אלקטרוני',
    'services.pricing.basic.features': '2 שירותים מוכלים, תמיכה בסיסית, תכונות מתקדמות, תמיכה במייל',
    
    'services.pricing.professional.plan': 'מקצועי',
    'services.pricing.professional.price': '299$',
    'services.pricing.professional.period': '/חודש',
    'services.pricing.professional.description': 'מושלם לעסקים נולדים עם צרכים שירות מספר',
    'services.pricing.professional.features': '4 שירותים מוכלים, תמיכה בעדיפות, תכונות מתקדמות, תמיכה בטלפון, האינטגרציה המותאמת',
    
    'services.pricing.enterprise.plan': 'ארגון',
    'services.pricing.enterprise.price': '799$',
    'services.pricing.enterprise.period': '/חודש',
    'services.pricing.enterprise.description': 'פתרון מלא לגודל מסחר גדול',
    'services.pricing.enterprise.features': 'כל 6 שירותים, תמיכה 24/7, האינטגרציה המותאמת, מנהל מותאם, אפשרויות מסגר',
    
    'services.testimonials.title': 'מה מומלץ על ידי מנהיגי התעשייה',
    'services.testimonials.subtitle': 'ראה מה הלקוחות שלנו אומרים על החוויה שלהם עם ShopHub',
    'services.testimonials.david.name': 'דייב צ\'ן',
    'services.testimonials.david.role': 'מנהל מסחר',
    'services.testimonials.david.company': 'טק טורב',
    'services.testimonials.david.content': 'מערכת ניהול הזמנות שלנו מפחיתה את זמן המעבדה ב-60% והסירה את השגיאות באופן מלא.',
    
    'services.testimonials.maria.name': 'מריה גרסיה',
    'services.testimonials.maria.role': 'מנהלת שיווק',
    'services.testimonials.maria.company': 'פאשן הב',
    'services.testimonials.maria.content': 'לוח הניתוח נתן לנו מידע שלא קיים לנו קודם לכן. מספר ההמרה עלה ב-40%.',
    
    'services.testimonials.james.name': 'ג\'יימס וילסון',
    'services.testimonials.james.role': 'המנהל',
    'services.testimonials.james.company': 'איקו סטור',
    'services.testimonials.james.content': 'האינטגרציה של תמיכת הלקוחות השינה את מספר מרצוננו מ-3.2 ל-4.8.',
    
    'services.stats.title': 'למה נבחרנו?',
    'services.stats.subtitle': 'מספרים שמספרים את סיפור ההצלחה שלנו',
    'services.stats.businesses.number': '500+',
    'services.stats.businesses.label': 'עסקות מומלצות',
    'services.stats.uptime.number': '99.9%',
    'services.stats.uptime.label': 'זמן פעילות',
    'services.stats.support.number': '24/7',
    'services.stats.support.label': 'תמיכה זמינה',
    'services.stats.orders.number': '50M+',
    'services.stats.orders.label': 'הזמנות מטופלות',
    
    // How It Works Section
    'services.howItWorks.step': 'שלב',
    
    // Contact Page
    'contact.title': 'צור קשר',
    'contact.subtitle': 'צור קשר איתנו',
    'contact.description': 'מוכן לשנות את עסק המסחר האלקטרוני שלך? צור קשר איתנו היום לייעוץ חינם.',
    'contact.form.name': 'שם מלא',
    'contact.form.email': 'כתובת דוא"ל',
    'contact.form.subject': 'נושא',
    'contact.form.message': 'הודעה',
    'contact.form.submit': 'שלח הודעה',
    'contact.info.address': 'כתובת',
    'contact.info.phone': 'טלפון',
    'contact.info.email': 'דוא"ל',
    
    // Blog Page
    'blog.title': 'תובנות אחרונות',
    'blog.subtitle': 'טרנדים וטיפים למסחר אלקטרוני',
    'blog.readMore': 'קרא עוד',
    'blog.backToBlog': 'חזור לבלוג',
    
    // Dashboard
    'dashboard.title': 'לוח בקרה',
    'dashboard.welcome': 'ברוך שובך',
    'dashboard.stats': 'סטטיסטיקות',
    'dashboard.recentOrders': 'הזמנות אחרונות',
    'dashboard.topProducts': 'מוצרים מובילים',
    'dashboard.quickActions': 'פעולות מהירות',
    
    // Footer
    'footer.description': 'מאפשרים הצלחת מסחר אלקטרוני עם פתרונות חדשניים ותמיכה יוצאת דופן.',
    'footer.quickLinks': 'קישורים מהירים',
    'footer.services': 'שירותים',
    'footer.company': 'חברה',
    'footer.support': 'תמיכה',
    'footer.newsletter': 'עיתון',
    'footer.newsletterPlaceholder': 'הזן את הדוא"ל שלך',
    'footer.newsletterSubscribe': 'הרשמה',
    'footer.copyright': '© 2024 Stackly24. כל הזכויות שמורות.',
    
    // Common
    'common.loading': 'טוען...',
    'common.error': 'אירעה שגיאה',
    'common.success': 'הצלחה!',
    'common.cancel': 'ביטול',
    'common.save': 'שמור',
    'common.edit': 'ערוך',
    'delete': 'מחק',
    'common.view': 'צפה',
    'common.back': 'חזור',
    'common.next': 'הבא',
    'common.previous': 'הקודם',
    'common.pleaseLogin': 'אנא התחבר כדי לגשת לדף זה',
    'common.mainMenu': 'תפריט ראשי',
    'common.selectLanguage': 'בחר שפה',
    'common.ecommerceLogo': 'לוגו מסחר אלקטרוני',
    'common.ctaBackground': 'רקע קריאה לפעולה',
    'common.googleMap': 'מפת גוגל',
    
    // Home2 Page Sections
    'home2.hero.title': 'פלטפורמת מסחר אלקטרוני',
    'home2.hero.subtitle': 'מודרנית',
    'home2.hero.description': 'שנה את העסק שלך עם פתרון המסחר האלקטרוני המתקדם שלנו. בנוי למהירות, אבטחה וסקלביליות.',
    'home2.hero.getStarted': 'התחל בחינם',
    'home2.hero.explore': 'חקור',
    'home2.hero.startJourney': 'התחל את המסע שלך',
    'home2.hero.joinThousands': 'הצטרף לאלפי עסקים מצליחים המשתמשים ב-ShopHub',
    'home2.hero.noSetupFees': 'אין דמי התקנה',
    'home2.hero.freeTrial': 'ניסיון חינם ל-14 יום',
    'home2.hero.cancelAnytime': 'ביטול בכל עת',
    
    // Home2 Hero Features
    'home2.hero.features.lightningFast': 'מהיר כבזק',
    'home2.hero.features.lightningFastDesc': 'בנוי למהירות וביצועים',
    'home2.hero.features.secureReliable': 'בטוח ואמין',
    'home2.hero.features.secureReliableDesc': 'אבטחה ברמת ארגון',
    'home2.hero.features.mobileFirst': 'עדיפות למובייל',
    'home2.hero.features.mobileFirstDesc': 'מעוצב לכל המכשירים',
    
    // Home2 Services Section
    'home2.services.title': 'כל מה שאתה צריך להצלחה',
    'home2.services.subtitle': 'פתרונות מסחר אלקטרוני מקיפים שנועדו לגדול את העסק שלך',
    'home2.services.ecommerce.title': 'פתרונות מסחר אלקטרוני',
    'home2.services.ecommerce.description': 'ניהול חנות מקוונת מלאה',
    'home2.services.ecommerce.feature1': 'קטלוג מוצרים',
    'home2.services.ecommerce.feature2': 'עיבוד הזמנות',
    'home2.services.ecommerce.feature3': 'שער תשלום',
    'home2.services.analytics.title': 'ניתוח ותובנות',
    'home2.services.analytics.description': 'החלטות עסקיות מבוססות נתונים',
    'home2.services.analytics.feature1': 'דוחות מכירות',
    'home2.services.analytics.feature2': 'ניתוח לקוחות',
    'home2.services.analytics.feature3': 'מדדי ביצוע',
    'home2.services.logistics.title': 'לוגיסטיקה ומשלוח',
    'home2.services.logistics.description': 'פעולות משלוח יעילות',
    'home2.services.logistics.feature1': 'ניהול מלאי',
    'home2.services.logistics.feature2': 'אינטגרציית משלוח',
    'home2.services.logistics.feature3': 'מערכות מעקב',
    'home2.services.payment.title': 'פתרונות תשלום',
    'home2.services.payment.description': 'עיבוד תשלום מאובטח',
    'home2.services.payment.feature1': 'שערים מרובים',
    'home2.services.payment.feature2': 'הגנה מפני הונאה',
    'home2.services.payment.feature3': 'חיוב חוזר',
    
    // Home2 Testimonials Section
    'home2.testimonials.title': 'מומלץ על ידי מנהיגי התעשייה',
    'home2.testimonials.subtitle': 'ראה מה הלקוחות שלנו אומרים על החוויה שלהם עם ShopHub',
    'home2.testimonials.alexandra.name': 'אלכסנדרה צ\'ן',
    'home2.testimonials.alexandra.role': 'מנכ"לית, TechStart',
    'home2.testimonials.alexandra.content': 'ShopHub שינה את העסק שלנו. ראינו עלייה של 300% במכירות מאז המעבר.',
    'home2.testimonials.marcus.name': 'מרקוס רודריגז',
    'home2.testimonials.marcus.role': 'מייסד, FashionHub',
    'home2.testimonials.marcus.content': 'הפלטפורמה אינטואיטיבית להפליא. הצוות שלנו היה פעיל ביום אחד בלבד.',
    'home2.testimonials.sarah.name': 'שרה קים',
    'home2.testimonials.sarah.role': 'מנהלת פעולות, EcoStore',
    'home2.testimonials.sarah.content': 'תמיכת לקוחות יוצאת דופן. הם עזרו לנו לגדול מ-100 ל-10,000 הזמנות חודשיות.',
    
    // Home2 Pricing Section
    'home2.pricing.title': 'מחירים פשוטים ושקופים',
    'home2.pricing.subtitle': 'בחר את התוכנית שמתאימה לצרכי העסק שלך. כל התוכניות כוללות את התכונות הבסיסיות שלנו.',
    'home2.pricing.starter.name': 'התחלה',
    'home2.pricing.starter.description': 'מושלם לעסקים קטנים',
    'home2.pricing.starter.price': '29$',
    'home2.pricing.starter.period': '/חודש',
    'home2.pricing.professional.name': 'מקצועי',
    'home2.pricing.professional.description': 'אידיאלי לעסקים צומחים',
    'home2.pricing.professional.price': '79$',
    'home2.pricing.professional.period': '/חודש',
    'home2.pricing.enterprise.name': 'ארגון',
    'home2.pricing.enterprise.description': 'לפעולות בקנה מידה גדול',
    'home2.pricing.enterprise.price': '199$',
    'home2.pricing.enterprise.period': '/חודש',
    'home2.pricing.mostPopular': 'הכי פופולרי',
    'home2.pricing.getStarted': 'התחל עכשיו',
    'home2.pricing.choosePlan': 'בחר תוכנית',
    'home2.pricing.features.upTo100': 'עד 100 מוצרים',
    'home2.pricing.features.upTo1000': 'עד 1000 מוצרים',
    'home2.pricing.features.unlimited': 'מוצרים ללא הגבלה',
    'home2.pricing.features.basicAnalytics': 'ניתוח בסיסי',
    'home2.pricing.features.advancedAnalytics': 'ניתוח מתקדם',
    'home2.pricing.features.customAnalytics': 'ניתוח מותאם אישית',
    'home2.pricing.features.emailSupport': 'תמיכה במייל',
    'home2.pricing.features.prioritySupport': 'תמיכה בעדיפות',
    'home2.pricing.features.support247': 'תמיכה 24/7',
    'home2.pricing.features.mobileApp': 'אפליקציה למובייל',
    'home2.pricing.features.apiAccess': 'גישה ל-API',
    'home2.pricing.features.customDomain': 'דומיין מותאם אישית',
    'home2.pricing.features.whiteLabel': 'פתרון מותג לבן',
    'home2.pricing.features.advancedIntegrations': 'אינטגרציות מתקדמות',
    
    // Home2 Stats Section
    'home2.stats.title': 'Shop במספרים',
    'home2.stats.subtitle': 'מומלץ על ידי עסקים ברחבי העולם עם תוצאות מוכחות',
    'home2.stats.productsSold': 'מוצרים נמכרו',
    'home2.stats.happyCustomers': 'לקוחות מרוצים',
    'home2.stats.countriesServed': 'מדינות שמוגשו',
    'home2.stats.uptimeGuarantee': 'ערבות זמן פעילות',
    
    // Home2 CTA Section
    'home2.cta.title': 'מוכן לשנות את העסק שלך?',
    'home2.cta.subtitle': 'הצטרף לאלפי עסקים מצליחים שסומכים על ShopHub להצלחת המסחר האלקטרוני שלהם. התחל את המסע שלך היום וגלה מה אפשרי.',
    'home2.cta.benefits.instantSetup.title': 'התקנה מיידית',
    'home2.cta.benefits.instantSetup.description': 'קבל את החנות שלך פועלת תוך דקות, לא ימים',
    'home2.cta.benefits.support247.title': 'תמיכה 24/7',
    'home2.cta.benefits.support247.description': 'הצוות המומחה שלנו כאן כדי לעזור לך להצליח',
    'home2.cta.benefits.scaleConfidence.title': 'גדל בביטחון',
    'home2.cta.benefits.scaleConfidence.description': 'בנוי להתמודד עם צמיחה מחברת סטארט-אפ לארגון',
    'home2.cta.knowMore': 'דע יותר',
    'home2.cta.scheduleDemo': 'תזמן הדגמה',
  },
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState<Language>('en');

  useEffect(() => {
    // Load saved language from localStorage
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && ['en', 'ar', 'he'].includes(savedLanguage)) {
      setCurrentLanguage(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setCurrentLanguage(lang);
    localStorage.setItem('language', lang);
    
    // Set document language without changing direction
    document.documentElement.lang = lang;
  };

  const t = (key: string): string => {
    return translations[currentLanguage][key as keyof typeof translations[typeof currentLanguage]] || key;
  };

  const isRTL = false; // RTL support removed

  useEffect(() => {
    // Set initial document language without changing direction
    document.documentElement.lang = currentLanguage;
  }, [currentLanguage]);

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
